source :rubygems
gem "sinatra", ">=1.0"
gem "rspec"
gem "data_mapper"
gem "rack-test"
gem "dm-core"
gem "dm-sqlite-adapter"
gem "dm-timestamps"
gem "dm-validations"
gem "dm-aggregates"
gem "dm-migrations"
gem "haml"
gem "tilt"
gem "fastthread"
gem "activesupport"
